# Site settings
title: Binary.com Developers
url: "https://morteza-binary.github.com/websockets"
twitter_username: binarydotcom
github_username:  binary-com

# Build settings
markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/
exclude:
  - Gemfile
  - Gemfile.lock
  - modules
  - Dockerfile
  - developers.com.conf
